[project]
name = "django-playground"
version = "0.1.0"
description = "A vanilla Django project to play around"
readme = "README.md"
requires-python = "==3.13.*"
dependencies = [
    "django>=5.2",
    "django-extensions>=4.1",
]
