# Generated by Django 5.2.dev20250426124613 on 2025-04-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("text", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("published_date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
