# Generated by Django 6.0.dev20250517104733 on 2025-05-17 10:47

from django.db import migrations, models


# sqlmigrate blog 0003
"""
BEGIN;
--
-- Remove field id from orderlineitem
--
CREATE TABLE "new__blog_orderlineitem" ("quantity" integer NOT NULL, "order_id" varchar(20) NOT NULL REFERENCES "blog_order" ("reference") DEFERRABLE INITIALLY DEFERRED, "product_id" bigint NOT NULL REFERENCES "blog_product" ("id") DEFERRABLE INITIALLY DEFERRED);
INSERT INTO "new__blog_orderlineitem" ("quantity", "order_id", "product_id") SELECT "quantity", "order_id", "product_id" FROM "blog_orderlineitem";
DROP TABLE "blog_orderlineitem";
ALTER TABLE "new__blog_orderlineitem" RENAME TO "blog_orderlineitem";
CREATE INDEX "blog_orderlineitem_order_id_44f585e9" ON "blog_orderlineitem" ("order_id");
CREATE INDEX "blog_orderlineitem_product_id_b0c377ad" ON "blog_orderlineitem" ("product_id");
--
-- Add field pk to orderlineitem
--
-- (no-op)
COMMIT;
"""


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_order_product_orderlineitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderlineitem",
            name="id",
        ),
        migrations.AddField(
            model_name="orderlineitem",
            name="pk",
            field=models.CompositePrimaryKey(
                "product_id",
                "order_id",
                blank=True,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
